# YetiMatch – Kotlin Multiplatform (Android + iOS)
workflows:
  android-kmp:
    name: Android (KMP)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - variables
      vars:
        PACKAGE_NAME: "com.daddoodev.yetimatch"
      android_signing:
        - codemagic_android_keystore
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
      
      - name: Fix gradlew permissions
        script: |
          chmod +x ./gradlew
      
      - name: Setup google-services.json (Android)
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > androidApp/google-services.json
  
      - name: Build Android (debug APK)
        script: |
          ./gradlew androidApp:assembleDebug

      - name: Build Android (release – production)
        script: |
          ./gradlew androidApp:assembleRelease androidApp:bundleRelease

    artifacts:
      - androidApp/build/outputs/apk/debug/*.apk
      - androidApp/build/outputs/apk/release/*.apk
      - androidApp/build/outputs/bundle/release/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  ios-kmp:
    name: iOS (KMP)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - variables
      vars:
        XCODE_WORKSPACE: "iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
        BUNDLE_ID: "com.daddoodev.yetimatch"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.daddoodev.yetimatch
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fix gradlew permissions
        script: |
          chmod +x ./gradlew
      
      - name: Setup GoogleService-Info.plist (iOS)
        script: |
          echo $GoogleServiceInfo | base64 --decode > iosApp/GoogleService-Info.plist
      
      - name: Sync version to iOS
        script: |
          ./gradlew syncVersionToIos

      - name: Build KMP iOS framework
        script: |
          ./gradlew composeApp:linkReleaseFrameworkIosArm64
      
      - name: Install CocoaPods
        script: |
          cd iosApp && pod install --repo-update

      - name: Set up code signing
        script: |
          PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null | head -1)
          if [ -z "$PROFILE_PATH" ]; then
            PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.provisionprofile 2>/dev/null | head -1)
          fi
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          TEAM_ID=$(/usr/libexec/PlistBuddy -c "Print :TeamIdentifier:0" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          echo "Profile UUID: $PROFILE_UUID"
          echo "Profile Name: $PROFILE_NAME"
          echo "Team ID: $TEAM_ID"
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          echo "CM_TEAM_ID=$TEAM_ID" >> $CM_ENV
          EP=/Users/builder/export_options.plist
          /usr/libexec/PlistBuddy -c "Clear dict" "$EP"
          /usr/libexec/PlistBuddy -c "Add :method string app-store" "$EP"
          /usr/libexec/PlistBuddy -c "Add :teamID string $TEAM_ID" "$EP"
          /usr/libexec/PlistBuddy -c "Add :uploadBitcode bool false" "$EP"
          /usr/libexec/PlistBuddy -c "Add :uploadSymbols bool true" "$EP"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles dict" "$EP"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:com.daddoodev.yetimatch string $PROFILE_NAME" "$EP"
          echo "Generated export_options.plist:"
          cat "$EP"

      - name: Build IPA
        script: |
          xcodebuild archive \
            -workspace "$CM_BUILD_DIR/iosApp/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/ios/YetiMatch.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$CM_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            CODE_SIGN_IDENTITY="Apple Distribution"
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/ios/YetiMatch.xcarchive" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa"

    artifacts:
      - build/ios/ipa/*.ipa

  both-platforms:
    name: Android + iOS (KMP)
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      groups:
        - variables
      vars:
        PACKAGE_NAME: "com.daddoodev.yetimatch"
        XCODE_WORKSPACE: "iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
        BUNDLE_ID: "com.daddoodev.yetimatch"
      android_signing:
        - codemagic_android_keystore
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.daddoodev.yetimatch
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties

      - name: Fix gradlew permissions
        script: |
          chmod +x ./gradlew

      - name: Setup google-services.json (Android)
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > androidApp/google-services.json

      - name: Setup GoogleService-Info.plist (iOS)
        script: |
          echo $GoogleServiceInfo | base64 --decode > iosApp/GoogleService-Info.plist

      - name: Sync version to iOS
        script: |
          ./gradlew syncVersionToIos

      - name: Build Android (debug APK)
        script: |
          ./gradlew androidApp:assembleDebug

      - name: Build Android (release – production)
        script: |
          ./gradlew androidApp:assembleRelease androidApp:bundleRelease

      - name: Build KMP iOS framework
        script: |
          ./gradlew composeApp:linkReleaseFrameworkIosArm64

      - name: Install CocoaPods
        script: |
          cd iosApp && pod install --repo-update

      - name: Set up code signing
        script: |
          PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null | head -1)
          if [ -z "$PROFILE_PATH" ]; then
            PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.provisionprofile 2>/dev/null | head -1)
          fi
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          TEAM_ID=$(/usr/libexec/PlistBuddy -c "Print :TeamIdentifier:0" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          echo "CM_TEAM_ID=$TEAM_ID" >> $CM_ENV
          EP=/Users/builder/export_options.plist
          /usr/libexec/PlistBuddy -c "Clear dict" "$EP"
          /usr/libexec/PlistBuddy -c "Add :method string app-store" "$EP"
          /usr/libexec/PlistBuddy -c "Add :teamID string $TEAM_ID" "$EP"
          /usr/libexec/PlistBuddy -c "Add :uploadBitcode bool false" "$EP"
          /usr/libexec/PlistBuddy -c "Add :uploadSymbols bool true" "$EP"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles dict" "$EP"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:com.daddoodev.yetimatch string $PROFILE_NAME" "$EP"

      - name: Build IPA
        script: |
          xcodebuild archive \
            -workspace "$CM_BUILD_DIR/iosApp/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/ios/YetiMatch.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$CM_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            CODE_SIGN_IDENTITY="Apple Distribution"
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/ios/YetiMatch.xcarchive" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa"

    artifacts:
      - androidApp/build/outputs/apk/debug/*.apk
      - androidApp/build/outputs/apk/release/*.apk
      - androidApp/build/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal