# YetiMatch – Kotlin Multiplatform (Android + iOS)
# See https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  android-kmp:
    name: Android (KMP)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.daddoodev.yetimatch"
      # Uncomment and set reference after uploading keystore in Team settings > Code signing > Android keystores:
      # android_signing:
      #   - yetimatch_keystore
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
      - name: Build Android (debug APK)
        script: |
          ./gradlew composeApp:assembleDebug
    artifacts:
      - composeApp/build/outputs/apk/debug/*.apk

  ios-kmp:
    name: iOS (KMP)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
        BUNDLE_ID: "com.daddoodev.yetimatch.YetiMatch"
      xcode: latest
      cocoapods: default
      # Uncomment and set after adding certificate + provisioning profile in Team settings > Code signing:
      # ios_signing:
      #   distribution_type: app_store
      #   bundle_identifier: com.daddoodev.yetimatch.YetiMatch
    scripts:
      - name: Build KMP iOS framework
        script: |
          ./gradlew composeApp:linkReleaseFrameworkIosArm64
      - name: Install CocoaPods
        script: |
          cd iosApp && pod install
      # Uncomment after adding code signing identities:
      # - name: Set up code signing
      #   script: xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/iosApp/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    # Uncomment to publish (email and/or App Store Connect):
    # publishing:
    #   email:
    #     recipients:
    #       - your@email.com
    #     notify:
    #       success: true
    #       failure: true
    #   app_store_connect:
    #     auth: integration
    #     submit_to_testflight: true
