# YetiMatch – Kotlin Multiplatform (Android + iOS)
workflows:
  android-kmp:
    name: Android (KMP)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - variables
      vars:
        PACKAGE_NAME: "com.daddoodev.yetimatch"
      android_signing:
        - codemagic_android_keystore
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
      
      - name: Fix gradlew permissions
        script: |
          chmod +x ./gradlew
      
      - name: Setup google-services.json (Android)
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > composeApp/google-services.json
  
      - name: Build Android (debug APK)
        script: |
          ./gradlew composeApp:assembleDebug

      - name: Build Android (release – production)
        script: |
          ./gradlew composeApp:assembleRelease composeApp:bundleRelease

    artifacts:
      - composeApp/build/outputs/apk/debug/*.apk
      - composeApp/build/outputs/apk/release/*.apk
      - composeApp/build/outputs/bundle/release/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  ios-kmp:
    name: iOS (KMP)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - variables
      vars:
        XCODE_WORKSPACE: "iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
        BUNDLE_ID: "com.daddoodev.yetimatch.YetiMatch"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fix gradlew permissions
        script: |
          chmod +x ./gradlew
      
      - name: Setup GoogleService-Info.plist (iOS)
        script: |
          echo $GoogleServiceInfo | base64 --decode > iosApp/GoogleService-Info.plist
      
      - name: Build KMP iOS framework
        script: |
          ./gradlew composeApp:linkReleaseFrameworkIosArm64
      
      - name: Install CocoaPods
        script: |
          cd iosApp && pod install
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/iosApp/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa