# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Google-Mobile-Ads-SDK'
  pod 'RevenueCat'
  pod 'RevenueCatUI'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
